### ISSUE TITLE
www.inoreader.com

### ISSUE THREAD

**Issue by wtser** [wtser/StyleHub#1]
```css
body {
  -webkit-font-smoothing: antialiased;
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial,
    sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol;
}

#reader_pane.reader_pane_sinner {
  padding-right: 0;
}
#no_more_div {
  height: 100vh !important;
  line-height: 100vh !important;
}

.ad_title_centered,
#article_dialog_modal_overlay + .inno_dialog {
  display: none !important;
}

#article_dialog_wrapper {
  height: 95vh !important;
  top: 50% !important;
  transform: translateY(-50%);
  overflow: hidden;
}


```
