### ISSUE TITLE
fulibus.net\/[\s\S]+.html

### ISSUE THREAD

**Issue by wtser** [wtser/StyleHub#3]
```css
.sidebar {display:none;}
.content {margin-right: 0;}

.entry-content img {
 max-width:100%;
}
```
